### ISSUE TITLE
获取不到href 值

### ISSUE THREAD

**Issue by guanhui07** [yan68/xcrawler#2]
用的第一个例子 ，php7.2.5 版本  dom_filter($node, 'a', 'attr','href')  获取不到 href 值

**Comment by guanhui07** [comment]
$node->filter('a').attr('href'); 这么可以获取到 dom_filter 函数不行

**Comment by yan68** [comment]
估计是php版本的问题？你运行demo可以获取到吗？

（我现在不在电脑前，回头试一下）

**Comment by yan68** [comment]
还有就是，dom_filter函数，解析别的数据OK吗（Html/其他属性之类的）

**Comment by yan68** [comment]
已在最新版本修复该问题，感谢反馈。

另，国内composer镜像更新可能有延迟。请耐心等待大概1天左右的时间。。
